### ISSUE TITLE
Does this just check the BIOS?

### ISSUE THREAD

**Issue by chrisridd** [rickyzhang82/ecc_check#1]
As I understand it, you can have ECC RAM, ECC support on the motherboard and chipset (BIOS), and ECC support in the CPU, and you need **all** of that to have working ECC.

What does your program actually do? The memory region you're reading seems to be part of the BIOS, so doesn't seem to check if the CPU supports ECC.

**Comment by rickyzhang82** [comment]
CPU datasheet should tell you if it supports ECC memory or not.

This check is for xeon e3 CPU if ECC is active or not:

See Page 219 on http://www.intel.com/content/www/us/en/processors/xeon/xeon-e3-1200-family-vol-2-
datasheet.html 

It may not apply to all CPU. Look up your CPU datasheet before using it.
